; Límites de subida y ejecución
upload_max_filesize=40M
post_max_size=40M
memory_limit=512M
max_execution_time=600
max_input_time=600

; Opcache para desarrollo
opcache.enable=1
opcache.enable_cli=1
opcache.validate_timestamps=1
opcache.revalidate_freq=2

; Reporte de errores
error_reporting=E_ALL
display_errors=On
